### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AlexanderFox777** [AlexanderFox777/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by date7887** [comment]
- I`m the main character of the BBC science fiction series "Doctor Who". I am a traveler in time and space who, together with various satellites, mostly modern people,  explore  the universe and fight injustice.

**Comment by AlexanderFox777** [comment]
Пойдет :)
