### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by AlexanderFox777** [AlexanderFox777/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by date7887** [comment]
### **FIRST DOCTOR**

Superman of World

**Comment by AlexanderFox777** [comment]
Супер
